"""Compile the contracts once, then always load the committed artifacts.

The build JSON (abi + bytecode) is committed so a demo, a fresh clone or CI
never depends on downloading the Solidity compiler.

Three contracts live here:

  FaceAnchorRegistry     v1. Stores an asserted similarity. Kept deployed and
                         working so the original demo record stays verifiable.
  Groth16Verifier        generated by snarkjs from the circuit. GPL-3.0, under
                         its own header; do not hand-edit, re-export it.
  FaceAnchorRegistryV2   refuses to store a record without a valid proof.

V2 needs `viaIR`: its twelve-argument Anchored event goes stack-too-deep under
the legacy pipeline. That is a codegen limit, not a design choice, so the flag
is set per contract rather than globally.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from pathlib import Path

from .. import config

SOLC_VERSION = "0.8.26"


@dataclass(frozen=True)
class Contract:
    name: str
    source: str
    via_ir: bool = False

    @property
    def source_path(self) -> Path:
        return config.CONTRACTS_DIR / self.source

    @property
    def build_path(self) -> Path:
        return config.CONTRACTS_DIR / "build" / f"{self.name}.json"


REGISTRY_V1 = Contract("FaceAnchorRegistry", "FaceAnchorRegistry.sol")
VERIFIER = Contract("Groth16Verifier", "Groth16Verifier.sol", via_ir=True)
REGISTRY_V2 = Contract("FaceAnchorRegistryV2", "FaceAnchorRegistryV2.sol", via_ir=True)

CONTRACTS = {c.name: c for c in (REGISTRY_V1, VERIFIER, REGISTRY_V2)}

# What `--registry v1|v2` maps to.
VERSIONS = {"v1": REGISTRY_V1, "v2": REGISTRY_V2}


def compile_contract(contract: Contract = REGISTRY_V1, write: bool = True) -> dict:
    """Compile with py-solc-x (downloads a prebuilt solc binary, no compiler)."""
    import solcx

    installed = [str(v) for v in solcx.get_installed_solc_versions()]
    if SOLC_VERSION not in installed:
        solcx.install_solc(SOLC_VERSION)

    settings: dict = {
        "optimizer": {"enabled": True, "runs": 200},
        "outputSelection": {"*": {"*": ["abi", "evm.bytecode.object", "metadata"]}},
    }
    if contract.via_ir:
        settings["viaIR"] = True

    out = solcx.compile_standard(
        {
            "language": "Solidity",
            "sources": {
                contract.source: {"content": contract.source_path.read_text(encoding="utf-8")}
            },
            "settings": settings,
        },
        solc_version=SOLC_VERSION,
    )
    c = out["contracts"][contract.source][contract.name]
    artifact = {
        "contractName": contract.name,
        "solcVersion": SOLC_VERSION,
        "optimizer": {"enabled": True, "runs": 200},
        "viaIR": contract.via_ir,
        "abi": c["abi"],
        "bytecode": "0x" + c["evm"]["bytecode"]["object"],
        "source": contract.source,
    }
    if write:
        artifact_path = contract.build_path
        artifact_path.parent.mkdir(parents=True, exist_ok=True)
        artifact_path.write_text(json.dumps(artifact, indent=2), encoding="utf-8")
    return artifact


def load_artifact(contract: Contract = REGISTRY_V1) -> dict:
    if contract.build_path.exists():
        return json.loads(contract.build_path.read_text(encoding="utf-8"))
    return compile_contract(contract)


def abi(contract: Contract = REGISTRY_V1) -> list:
    return load_artifact(contract)["abi"]


def resolve(version: str) -> Contract:
    if version not in VERSIONS:
        raise SystemExit(f"unknown registry version '{version}'. choose from: "
                         + ", ".join(VERSIONS))
    return VERSIONS[version]
